### ISSUE TITLE
Secureworker-create does not work

### ISSUE THREAD

**Issue by stefanionescu** [evervault/node-secureworker#16]
Running "node tests/run.js" gives the following:

`Error: Command failed: make enclave SCRIPTS=/home/stefan/Work/ForOthers/node-secureworker/tests/test.js /home/stefan/Work/ForOthers/node-secureworker/tests/test-commands.js ENCLAVE_KEY=/home/stefan/Work/ForOthers/node-secureworker/tests/key.pem ENCLAVE_CONFIG=/home/stefan/Work/ForOthers/node-secureworker/tests/enclave.config.xml ENCLAVE_OUTPUT=/home/stefan/Work/ForOthers/node-secureworker/tests/enclave.so
    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Object.<anonymous> (/home/stefan/Work/ForOthers/node-secureworker/bin/secureworker-create:34:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
child_process.js:624
    throw err;`

Note that I want to build this enclave and then execute it in simulation/mock mode as I do not have SGX on my machine

**Comment by shanecurran** [comment]
Hi Stefan, would you mind trying `npm run build` in the root of the module directory?

**Comment by stefanionescu** [comment]
Hey @shanecurran , it was a long time ago, I moved past this stuff. I can close the issue if you want
