### ISSUE TITLE
Unable to run in simulation mode, only mock mode

### ISSUE THREAD

**Issue by jason-james** [evervault/node-secureworker#24]
My program is working fine in mock mode, however I'd like to run in simulation mode to make use of the `enclave.so` file. When I run it, it says it can't find ` libsgx_urts_sim.so` as below. 

> Could not load SGX secure worker binary:
> Error: libsgx_urts_sim.so: cannot open shared object file: No such file or directory
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1133:18)
>     at Module.load (internal/modules/cjs/loader.js:914:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
>     at Module.require (internal/modules/cjs/loader.js:956:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/home/jason/WebstormProjects/sgx-test/node_modules/secureworker/lib/real.js:1:28)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
>     at Module.load (internal/modules/cjs/loader.js:914:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
> Mock implementation will be used instead. Do not use in production.

This issue is solved by others (presumably not using secureworker) by ensuring their environment variables are set and if that doesn't work then setting a file in `r /etc/ld.so.conf.d` and running `ldconfig`, but this doesn't work in my case. Any suggestions? Is simulation mode supposed to work with this package? The file its referring to definitely exists.

**Comment by jason-james** [comment]
Additional question:

Is it possible to use SecureWorker.importScripts in mock mode? I have tried what feels like everything, and looked at the Luckychain implementation, but I keep getting an error like this:

>self.pointInPolygon = require('@turf/boolean-point-in-polygon')
^

> ReferenceError: require is not defined
>     at enclave-imports.js:1:1
>     at Script.runInContext (vm.js:127:20)
>     at Object.runInContext (vm.js:290:6)
>     at Object.importScripts (/home/jason/WebstormProjects/sgx-test/node_modules/secureworker/lib/mock.js:213:16)
>     at hello-world-from-enclave.js:2:14
>     at Script.runInContext (vm.js:127:20)
>     at Object.runInContext (vm.js:290:6)
>     at SecureWorker.createdCallback (/home/jason/WebstormProjects/sgx-test/node_modules/secureworker/lib/mock.js:33:6)
>     at new SecureWorker (/home/jason/WebstormProjects/sgx-test/node_modules/secureworker/lib/mock.js:17:8)
>     at enclaveConstructor (/home/jason/WebstormProjects/sgx-test/hello-world.js:6:20)
